### ISSUE TITLE
Handle No Internet Connection

### ISSUE THREAD

**Issue by frishkorn** [frishkorn/lotteryNumbers#35]
When behind a firewall for example the following error message is shown.

`Traceback (most recent call last):
  File "lottoAnalysis.py", line 63, in <module>
    lottoAnalyze()
  File "lottoAnalysis.py", line 28, in lottoAnalyze
    numData = lottoList()
  File "lottoAnalysis.py", line 9, in lottoList
    lottoDatabase.lottoData()
  File "/Users/frishkorn/home/python/lotteryNumbers/lottoDatabase.py", line 11, in lottoData
    urllib.request.urlretrieve(url, 'winnums-text.txt') 
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
`

Instead it would be better to simply show a small error message.

**Comment by frishkorn** [comment]
A simple message is now shown instead of failing module. This was accomplished using sys.exit().
